### ISSUE TITLE
api > npm start > 'jsonwebtoken'

### ISSUE THREAD

**Issue by najandz** [adhithiravi/Consuming-GraphqL-Apollo#1]
Hi, first of all, thank you for the excellent material, 

I am getting this error when I run npm start inside API > Error: Cannot find module 'jsonwebtoken', any idea how to resolve it?

Cheers,

**Comment by adhithiravi** [comment]
Hi Thank you!

Have you installed all the dependencies? npm install both inside app and api folders as well as for the overall package.json file as well?

**Comment by najandz** [comment]
Thanks for your quick reply, fixed, forgot to run in the overall package.json file.
